name: Send Daily Telegram Message

on:
  schedule:
    - cron: '0 19 * * *' # Every day at 6PM GMT
  workflow_dispatch: # Allows manual runs

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use a modern Python version

      - name: Install requests
        run: pip install requests

      - name: Run Telegram Bot Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE: ${{ secrets.MESSAGE }}
        run: python send_message.py
