name: Send Daily Telegram Message

on:
  schedule:
    - cron: '0 9 * * *' # Every day at 09:00 UTC
  workflow_dispatch: # allows manual run

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram Message Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE: ${{ secrets.MESSAGE }}
        run: python send_message.py
